=== Darioorg10/LenguajeDeMarcas/XML/Relacion_Final/Ejercicio20_y_21/MOTORSOL.dtd
<!ELEMENT motor (pieza | empleados)+>
<!ELEMENT pieza (#PCDATA)>
<!ELEMENT empleados (responsable, comunes, familiaresACargo)>
<!ELEMENT responsable (#PCDATA)>
<!ELEMENT comunes (comun)+>
<!ELEMENT familiaresACargo (hermanos | primos | abuelos)>
<!ELEMENT hermanos (#PCDATA)>
<!ELEMENT primos (#PCDATA)>
<!ELEMENT abuelos (#PCDATA)>

=== Darioorg10/LenguajeDeMarcas/XML/Relacion_Final/Ejercicio20_y_21/MOTORSOL.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE motor SYSTEM "MOTORSOL.dtd">
<motor>
    <pieza>
        Cilindro
    </pieza>
    <pieza>
        Tubo
    </pieza>    
    <empleados>
        <responsable>Manolo García</responsable>
        <comunes>
            <comun>Juan Gabriel</comun>
            <comun>Pepe Domínguez</comun>
        </comunes>
        <familiaresACargo>
            <hermanos>0</hermanos>
            <primos>2</primos>
            <abuelos>4</abuelos>
        </familiaresACargo>
    </empleados>
</motor>
