<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fabrica [
<!ELEMENT fabrica (piezas, motores, secciones, empleados)>
<!ELEMENT piezas (pieza+)>
<!ELEMENT pieza EMPTY>
    <!ATTLIST pieza id ID #REQUIRED
              compuesta IDREFS #IMPLIED> <!-- Puede aparecer mÃ¡s de una vez -->
<!ELEMENT motores (motor+)>
<!ELEMENT motor (trabajador+)>
    <!ATTLIST motor id ID #REQUIRED
                    responsable IDREF #REQUIRED
                    piezas IDREFS #REQUIRED>
<!ELEMENT trabajador EMPTY> 
    <!ATTLIST trabajador cod IDREF #REQUIRED
                         familiares IDREFS #IMPLIED>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion EMPTY>
    <!ATTLIST seccion cod ID #REQUIRED
                    realiza IDREFS #REQUIRED>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado EMPTY>
    <!ATTLIST empleado nif ID #REQUIRED>
]>

<fabrica>
    <piezas>
        <pieza id="p1" compuesta="p2 p3"/>
        <pieza id="p2"/>
        <pieza id="p3"/>
        <pieza id="p4"/>
    </piezas>
    <motores>
        <motor id="m1" responsable="_11111111N" piezas="p1 p4">
            <trabajador cod="_11111111N"/>
            <trabajador cod="_22222222N" familiares="_33333333N _44444444N"/>
        </motor>
        <motor id="m2" responsable="_22222222N" piezas="p3">
            <trabajador cod="_11111111N"/>
            <trabajador cod="_22222222N" familiares="_33333333N"/>
        </motor>
        <motor id="m3" responsable="_44444444N" piezas="p2">
            <trabajador cod="_44444444N"/>
            <trabajador cod="_55555555N" familiares="_66666666N"/>
        </motor>
    </motores>
    <secciones>
        <seccion cod="s1" realiza="m1 m2"/>                
        <seccion cod="s2" realiza="m3"/>                
    </secciones>
    <empleados>
        <empleado nif="_11111111N"/>
        <empleado nif="_22222222N"/>
        <empleado nif="_33333333N"/>
        <empleado nif="_44444444N"/>
        <empleado nif="_55555555N"/>
        <empleado nif="_66666666N"/>
    </empleados>
</fabrica>
