=== Darioorg10/LenguajeDeMarcas/Schemas/Ejemplo1(Introduccion)/nota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="notas">
        <xs:complexType>
            <xs:sequence> <!-- Si ponemos xs:all es que da igual el orden, sequence al ser una secuencia tiene que ir en ese orden -->
                <xs:element name="nota" maxOccurs="unbounded"> <!-- Para poner todas las notas que quieras-->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="a" type="xs:string"/>
                            <xs:element name="de" type="xs:string"/>
                            <xs:element name="cabecera" type="xs:string"/>
                            <xs:element name="cuerpo" type="xs:string"/>
                            <xs:element name="fin" type="xs:string" minOccurs="0"/> <!-- Esto es para que pueda aparecer o no-->            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

<!-- Forma más fácil/mejor de hacerlo-->
<xs:schema xmlns:xs="http://w3.org/2001/XMLSchema">
    
    <xs:element name="notas" type="tipoNotas"/>

    <xs:complexType name="tipoNotas">
        <xs:sequence>
            <xs:element name="nota" type="tipoNota" maxOccurs="unbounded"/>                     
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoNota">
        <xs:sequence>
            <xs:element name="a" type="xs:string"/>
            <xs:element name="de" type="xs:string"/>
            <xs:element name="cabecera" type="xs:string"/>
            <xs:element name="cuerpo" type="xs:string"/>
            <xs:element name="fin" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Darioorg10/LenguajeDeMarcas/Schemas/Ejemplo1(Introduccion)/Mal_Hecho_Pero_Explicado/nota.xml
<?xml version="1.0" encoding="UTF-8"?>
<notas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nota.xsd"> <!-- El xsi es un alias, podrías ponerle pepe -->
    <nota>
        <a>Juan</a>
        <de>Susana</de>
        <cabecera>Recordatorio</cabecera>
        <cuerpo>¡Recuerda que tenemos reunión!</cuerpo>
        <fin>Atentamente, Susana</fin>
    </nota>
    <nota>
        <a>Susana</a>
        <de>Juan</de>
        <cabecera>Recordatorio</cabecera>
        <cuerpo>¡Recuerda que tenemos reunión!</cuerpo>
    </nota>
    
</notas>
